### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [gipsonsa/Week-5-DRY-ERB#1]
It looks like your hosted URL is just pointing to your GitHub repo. Can you update your showcase to point to the URL, let me know here when it's done?

**Comment by gipsonsa** [comment]
Sorry about this. I completely forgot that we were supposed to host our apps on heroku. Hard to forget I know haha. Thank you for notifying me on this! I’m finishing up the other portion of this week’s assignments right now so I’ll let you know when that is done.

Sam

**Comment by chrisvfritz** [comment]
:+1: Looking much better!

## Points of improvement for future projects

### Getting rid of `.DS_Store` clutter

OS X automatically generates hidden `.DS_Store` files and by default, Git will include them your commits. To get rid of this clutter in our Git repos, you can [check out this link](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).
